title: Hoofbeats Health
short-title: Hoofbeats
email: HoofbeatsHealth
description: the digital toolbox for your healthcare
baseurl: ""
url: "https://hoofbeats.github.io"
twitter_username: HoofbeatsHealth
github_username:  Hoofbeats
anchor_username: HoofbeatsHealth

# Build settings
markdown: kramdown
permalink: /:year/:title/
collections:
  visuals:
    output: true
    permalink: /:collection/:name/
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
